{% set name = "doepipeline" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/clicumu/doepipeline/archive/v{{ version }}.tar.gz
  sha256: f02c92912d979f28b4f49ccfd15f781f6498bc3f40e2286bb747505254d0be36

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  skip: True  # [win]

requirements:
  host:
    - python >=3
    - pip

  run:
    - python >=3
    - pandas
    - pydoe2
    - pyyaml
    - statsmodels

test:
  imports:
    - doepipeline
    - doepipeline.executor

  commands: 
    - doepipeline --help

about:
  home: https://github.com/clicumu/doepipeline
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Package for optimizing pipelines using DoE.

extra:
  recipe-maintainers:
    - druvus
